config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :coupons
  devise_for :users, :controllers => { :registrations => 'registrations' }
  resources :users
  root :to => 'visitors#index'
end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  has_many :users
  validates :code, inclusion: { in: Coupon.pluck('DISTINCT code'),
      message: "value is not a valid coupon code" }
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?
  after_validation :set_coupon

  belongs_to :coupon
  accepts_nested_attributes_for :coupon
  validates_associated :coupon

  def set_default_role
    self.role ||= :user
  end

  def name
    "Application User"
  end

  def set_coupon
    return false if errors.any?
    return false if self.coupon.nil?
    coupon = Coupon.find_by code: self.coupon.code
    self.coupon = coupon
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def charge_card
    if !self.stripe_token.present?
      self.errors[:base] << 'Could not verify card.'
      raise ActiveRecord::RecordInvalid.new(self)
    end
     customer = Stripe::Customer.create(
      :email => self.email,
      :card => self.stripe_token
    )

    price = self.coupon.nil? ?
      Product.last.price : self.coupon.price
    title = Product.last.name
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => "#{price}",
      :description => "#{title}",
      :currency    => 'usd'
    )
    self.stripe_token = nil
    Rails.logger.info("Stripe transaction for #{self.email}") if charge[:paid] == true
  rescue Stripe::InvalidRequestError => e
    self.errors[:base] << e.message
    PaymentFailureMailer.failed_payment_email(self).deliver_now
    self.destroy
  rescue Stripe::CardError => e
    self.errors[:base] << e.message
    PaymentFailureMailer.failed_payment_email(self).deliver_now
    self.destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  before_action :set_coupon, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :admin_only

  respond_to :html

  def index
    @coupons = Coupon.all
    respond_with(@coupons)
  end

  def show
    respond_with(@coupon)
  end

  def new
    @coupon = Coupon.new
    respond_with(@coupon)
  end

  def edit
  end

  def create
    @coupon = Coupon.new(coupon_params)
    @coupon.save(validate: false)
    respond_with(@coupon)
  end

  def update
    @coupon = Coupon.find(params[:id])
    @coupon.attributes = coupon_params
    @coupon.save(validate: false)
    respond_with(@coupon)
  end

  def destroy
    @coupon.destroy
    respond_with(@coupon)
  end

  private
    def set_coupon
      @coupon = Coupon.find(params[:id])
    end

    def coupon_params
      params.require(:coupon).permit(:code, :role, :mailing_list_id, :list_group, :price)
    end

    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Access denied."
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :identify_product

  def show
    send_file @path, :disposition => "attachment; filename=#{@file}"
  end

  private
  def identify_product
    valid_characters = "^[0-9a-zA-Z]*$".freeze
    unless params[:id].blank?
      @product_id = params[:id]
      @product_id = @product_id.tr("^#{valid_characters}", '')
    else
      raise "Filename missing"
    end
    unless params[:format].blank?
      @format = params[:format]
      @format = @format.tr("^#{valid_characters}", '')
    else
      raise "File extension missing"
    end
    @path = "app/views/products/#{@product_id}.#{@format}"
    @file = "#{@product_id}.#{@format}"
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protect_from_forgery :except => :create
  after_action :process_order, :only => :create

  def new
    build_resource({})
    yield resource if block_given?
    self.resource.coupon = Coupon.new
    respond_with self.resource
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation,
      :stripe_token, {coupon_attributes: [:code]})
  end

  def process_order
    return if resource.admin?
    if resource.persisted?
      PaymentJob.perform_later(resource) unless resource.coupon.price == 0
      MailingListSignupJob.perform_later(resource)
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @resource = User.new
    @resource.coupon = Coupon.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/coupons/_form.html.erb
<%= form_for(@coupon) do |f| %>
  <% if @coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% @coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :mailing_list_id %><br>
    <%= f.text_field :mailing_list_id %>
  </div>
  <div class="field">
    <%= f.label :list_group %><br>
    <%= f.text_field :list_group %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Role</th>
      <th>Mailing list</th>
      <th>List group</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.code %></td>
        <td><%= coupon.role %></td>
        <td><%= coupon.mailing_list_id %></td>
        <td><%= coupon.list_group %></td>
        <td><%= coupon.price %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @coupon.code %>
</p>

<p>
  <strong>Role:</strong>
  <%= @coupon.role %>
</p>

<p>
  <strong>Mailing list:</strong>
  <%= @coupon.mailing_list_id %>
</p>

<p>
  <strong>List group:</strong>
  <%= @coupon.list_group %>
</p>

<p>
  <strong>Price:</strong>
  <%= @coupon.price %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path, data: { no_turbolink: true } %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'Coupons', coupons_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', page_path('about') %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
          <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
        <% else %>
          <li><%= link_to 'Sign in', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path, data: { no_turbolink: true } %></li>
        <% end %>
        <% if user_signed_in? %>
          <% if current_user.try(:admin?) %>
            <li><%= link_to 'Users', users_path %></li>
            <li><%= link_to 'Coupons', coupons_path %></li>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Stripe Coupons" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Stripe Coupons" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/pages/downloads.html.erb
<div class="authform">
  <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form', :class => 'payment-form'}) do |f| %>
    <h3>Free Download</h3>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
    </div>
    <div class="form-group">
      <label for="user_coupon_attributes_code">Invitation code</label>
      <input class="form-control" type="text" name="user[coupon_attributes][code]" id="user_coupon_attributes_code" />
    </div>
    <p>No invitation code? You can <%= link_to 'purchase the book', root_path %>.</p>
    <%= f.submit 'Sign up', :class => 'button right' %>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.status %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/_purchase.html.erb
<br />
<a href="#" class="btn btn-primary" data-toggle="modal" data-target="#purchaseModal">Purchase</a>
<div class="modal fade" id="purchaseModal" tabindex="-1" role="dialog" aria-labelledby="purchaseModal" aria-hidden="true">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <% content_for :head do %>
        <%= render 'devise/registrations/javascript' %>
      <% end %>
      <div class="authform">
        <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :html => { :role => 'form', :class => 'payment-form'}) do |f| %>
          <h3>Sign up</h3>
          <div id='stripe_error' class='alert alert-danger' style='display:none' ></div>
          <%= devise_error_messages! %>
          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          <% if resource.stripe_token %>
            <p>Credit card acceptance is pending.</p>
          <% else %>
            <div class="form-group">
              <%= label_tag :card_number, "Credit Card Number" %>
              <%= text_field_tag :card_number, nil, name: nil, class: 'form-control', data: { stripe: 'number' } %>
            </div>
            <div class="form-group">
              <%= label_tag :card_code, "Card Security Code" %>
              <%= text_field_tag :card_code, nil, name: nil, class: 'form-control', data: { stripe: 'cvc' } %>
            </div>
            <br />
            <div class="form-group">
              <%= label_tag :card_month, "Card Expiry" %>
              <%= select_month nil, { use_two_digit_numbers: true}, { name: nil, data: {stripe: 'exp-month' } } %>
              <%= select_year nil, {start_year: Date.today.year, end_year: Date.today.year+10}, { name: nil, data: {stripe: 'exp-year' } } %>
            </div>
          <% end %>
          <br />
          <%= f.fields_for :coupon do |ff| %>
            <div class="form-group">
              <%= ff.label 'Coupon code' %>
              <%= ff.text_field :code, :class => 'form-control' %>
            </div>
          <% end %>
          <%= f.hidden_field :stripe_token %>
          <%= f.submit 'Sign up', :class => 'button right' %>
        <% end %>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <h3>Admin</h3>
    <p><%= link_to 'User count:', users_path %> <%= User.count %></p>
  <% else %>
    <h3>Download the book.</h3>
    <%= link_to 'Download PDF', products_path('product.pdf'), :class => 'btn btn-success btn-large' %>
  <% end %>
<% else %>
  <% Product.where(status: 'Available').each do |p| %>
    <h3>Purchase <%= "#{p.name}" %> </h3>
    <article>
      <label class="amount">
        <%= image_tag 'rubyonrails.png', size: '60x60' %>

        <div><%= p.name %></div>
        <div><%= p.price.to_f %></div>

      </label>
      <%= render :partial => 'purchase' %>
    </article>
  <% end %>
<% end %>